openapi: 3.0.0
servers:
  - description: ローカルホスト
    url: http://localhost
info:
  version: "1.0.0"
  title: 飲料情報共有サイトのAPI
paths:
  /drink:
    get:
      tags:
        - developers
      summary: searches inventory
      operationId: searchInventory
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      parameters:
        - in: query
          name: searchString
          description: pass an optional search string for looking up inventory
          required: false
          schema:
            type: string
        - in: query
          name: name
          description: number of drinnks
          schema:
            type: string
        - in: query
          name: price
          description: price of drinks
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 100000
        - in: query
          name: place
          description: place we able to drink
          schema:
            type: string
        - in: query
          name: rate
          description: evaluation of drink
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 5
        - in: query
          name: category
          description: category of drink
          schema:
            type: string
        - in: query
          name: memo
          description: memo
          schema:
            type: string
      responses:
        '200':
          description: show detail of drink
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Drink'
        '400':
          description: bad input parameter
        '404':
          description: not found page
        '500':
          description: internal server error
    post:
      summary: adds an drink information
      operationId: addDrink
      description: Adds an item to the system
      responses:
        '201':
          description: item created
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing item already exists
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Drink'
        description: Drink to add
components:
  schemas:
    Drink:
      type: object
      required:
        - name
        - price
        - place
        - rate
        - category
        - memo
      properties:
        name:
          type: string
          example: 'Guiness Beer'
        price:
          type: integer
          format: int32
          example: 1000
        place:
          type: string
          example: 'Ginza Bar'
        rate:
          type: integer
          format: int32
          example: 3
        category:
          type: string
          example: 'Beer'
        memo:
          type: string
          example: 'The most famous black beer'