openapi: 3.0.0
servers:
  - description: ローカルホスト
    url: http://localhost
info:
  version: "1.0.0"
  title: 飲料情報共有サイトのAPI
paths:
  /drink:
    get:
      summary: findall
      operationId: findalldrink
      description: |
        findall drink information
      parameters:
        
      responses:
        '200':
          description: show detail of drink
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Drink'
        '400':
          description: bad input parameter
        '404':
          description: not found page
        '500':
          description: internal server error
    post:
      summary: adds an drink information
      operationId: addDrink
      description: Adds an item to the system
      responses:
        '201':
          description: item created
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing item already exists
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Drink'
        description: Drink to add
components:
  schemas:
    Drink:
      type: object
      required:
        - name
        - price
        - place
        - rate
        - category
        - memo
      properties:
        name:
          type: string
          example: 'Guiness Beer'
        price:
          type: integer
          format: int32
          example: 1000
        place:
          type: string
          example: 'Ginza Bar'
        rate:
          type: integer
          format: int32
          example: 3
        category:
          type: string
          example: 'Beer'
        memo:
          type: string
          example: 'The most famous black beer'